# -*- coding: utf-8 -*-
"""Copy of Comp_Sec_Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1shgN5wqWxh-NFzkhWw22QbFr9oBKHqUA

# Install the required Packages
"""

# pip install pycryptodome

from Crypto.PublicKey import RSA
from Crypto.Signature import pkcs1_15
from Crypto.Hash import SHA256

# Generate keys
key = RSA.generate(2048)
private_key = key
public_key = key.publickey()

# Wrong keys generated
key2 = RSA.generate(1024)
public_key2 = key2.publickey()

# Message
message = b"Hello, this is a secure message"

# Hash message
h = SHA256.new(message)

# Sign
signature = pkcs1_15.new(private_key).sign(h)
# print(signature)

# Verify
print("Valid Key Part.")
try:
    pkcs1_15.new(public_key).verify(h, signature)
    print("Signature is valid")
except:
    print("Signature is NOT valid")

# Validate incorrectness
print("\nInvalid Key Part.")
try:
    pkcs1_15.new(public_key2).verify(h, signature)
    print("Signature is valid")
except:
    print("Signature is NOT valid")